/*
 * Copyright (c) 2021 iSoftStone Device Co., Ltd.
 *
 * HDF is dual licensed: you can use it either under the terms of
 * the GPL, or the BSD license, at your option.
 * See the LICENSE file in the root of this repository for complete details.
 */
/*import {LifeIndex} from './whetherDataDetail'

export function initializeOnStartup4():LifeIndex{
  let lifeIndex : LifeIndex
  lifeIndex = new LifeIndex(lifeComposition.humidity,lifeComposition.sentemp,lifeComposition.windpower,lifeComposition.winddirection,lifeComposition.dressing,lifeComposition.motion,lifeComposition.cold,lifeComposition.uv,lifeComposition.carwash,lifeComposition.gofishing,lifeComposition.allergy,lifeComposition.pavementcon,lifeComposition.sunscreen,lifeComposition.airing,lifeComposition.morningexer,lifeComposition.traffic)

  return lifeIndex
}

const lifeComposition : LifeIndex = {'humidity':39,'sentemp':35,'windpower':'微风','winddirection':'西北风','dressing':'短袖','motion':'适宜','cold':'不易','uv':'弱','carwash':'适宜','gofishing':'不宜','allergy':'不易发','pavementcon':'干燥','sunscreen':'中等','airing':'较适宜','morningexer':'较适宜','traffic':'良好'}*/
