/*
# Copyright (c) 2020-2030 iSoftStone Information Technology (Group) Co.,Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
*/
/*import {LifeIndex} from './whetherDataDetail'

export function initializeOnStartup4():LifeIndex{
  let lifeIndex : LifeIndex
  lifeIndex = new LifeIndex(lifeComposition.humidity,lifeComposition.sentemp,lifeComposition.windpower,lifeComposition.winddirection,lifeComposition.dressing,lifeComposition.motion,lifeComposition.cold,lifeComposition.uv,lifeComposition.carwash,lifeComposition.gofishing,lifeComposition.allergy,lifeComposition.pavementcon,lifeComposition.sunscreen,lifeComposition.airing,lifeComposition.morningexer,lifeComposition.traffic)

  return lifeIndex
}

const lifeComposition : LifeIndex = {'humidity':39,'sentemp':35,'windpower':'微风','winddirection':'西北风','dressing':'短袖','motion':'适宜','cold':'不易','uv':'弱','carwash':'适宜','gofishing':'不宜','allergy':'不易发','pavementcon':'干燥','sunscreen':'中等','airing':'较适宜','morningexer':'较适宜','traffic':'良好'}*/
