# SPDX-License-Identifier: GPL-2.0

snd-soc-dummy-codec-objs := dummy-codec.o
snd-soc-rk-codec-digital-objs := rk_codec_digital.o

obj-$(CONFIG_SND_SOC_DUMMY_CODEC)	+= snd-soc-dummy-codec.o
obj-$(CONFIG_SND_SOC_RK_CODEC_DIGITAL)	+= snd-soc-rk-codec-digital.o
